import React, { useState, useEffect } from 'react';
import { useOutletContext } from 'react-router-dom';
import { IndianRupee, CreditCard, Clock, BadgePercent, CheckCircle, HelpCircle, FileText, Globe } from 'lucide-react';

const EarningTab = () => {
  const { currentUser, myPerformanceDetails } = useOutletContext();
  const [payouts, setPayouts] = useState([]);
  const [loadingPayouts, setLoadingPayouts] = useState(true);
  const [activeSubTab, setActiveSubTab] = useState('commissions'); // 'commissions' | 'payouts'

  const employee = currentUser?.employeeDetails || {};
  
  // Commission summary from performance details (calculated dynamically from store billing history)
  const totalCommission = myPerformanceDetails?.totalCommission || 0;
  const onboardedStores = myPerformanceDetails?.stores || [];
  const commissionPercentage = myPerformanceDetails?.performanceSettings?.commissionPercentage || 10;

  // Fetch payout invoices generated by administrator
  useEffect(() => {
    const fetchPayouts = async () => {
      try {
        const token = localStorage.getItem('superadmin_token') || localStorage.getItem('token');
        if (!token) return;

        const envUrl = (import.meta.env.VITE_API_URL || 'http://localhost:3011').replace(/\/api\/superadmin\/?$/, '').replace(/\/$/, '');
        const res = await fetch(`${envUrl}/api/staff-performance/my-payouts`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (res.ok) {
          setPayouts(await res.json());
        }
      } catch (err) {
        console.error("Failed to fetch payouts:", err);
      } finally {
        setLoadingPayouts(false);
      }
    };

    fetchPayouts();
  }, []);

  // Calculate earnings metrics
  // Total paid payouts (both salary and commission payouts)
  const totalPaidPayouts = payouts.reduce((sum, item) => sum + (item.amount || 0), 0);
  const commissionPayouts = payouts.filter(p => p.type === 'commission').reduce((sum, item) => sum + (item.amount || 0), 0);
  const pendingPayouts = Math.max(totalCommission - commissionPayouts, 0);

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Earnings Metrics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 flex items-center gap-4">
          <div className="p-3 bg-blue-50 rounded-xl text-blue-600">
            <IndianRupee size={24} />
          </div>
          <div>
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Total Commission Earned</h4>
            <p className="text-2xl font-extrabold text-slate-800">₹{totalCommission.toLocaleString('en-IN')}</p>
            <p className="text-[10px] text-slate-400 font-semibold mt-0.5">Calculated at {commissionPercentage}% rate</p>
          </div>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 flex items-center gap-4">
          <div className="p-3 bg-green-50 rounded-xl text-green-600">
            <CheckCircle size={24} />
          </div>
          <div>
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Payouts Cleared</h4>
            <p className="text-2xl font-extrabold text-slate-800">₹{totalPaidPayouts.toLocaleString('en-IN')}</p>
            <p className="text-[10px] text-slate-400 font-semibold mt-0.5">Salary & commission invoices paid</p>
          </div>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 flex items-center gap-4">
          <div className="p-3 bg-amber-50 rounded-xl text-amber-600">
            <Clock size={24} />
          </div>
          <div>
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Unpaid Commission</h4>
            <p className="text-2xl font-extrabold text-slate-800">₹{pendingPayouts.toLocaleString('en-IN')}</p>
            <p className="text-[10px] text-slate-400 font-semibold mt-0.5">Pending monthly invoice release</p>
          </div>
        </div>
      </div>

      {/* Sub Tabs for Earnings Breakdown */}
      <div className="flex gap-4 border-b border-slate-200 pb-3">
        <button 
          onClick={() => setActiveSubTab('commissions')}
          className={`pb-2 text-sm font-bold transition-all relative ${activeSubTab === 'commissions' ? 'text-blue-600 font-extrabold border-b-2 border-blue-600' : 'text-slate-500 hover:text-slate-800'}`}
        >
          Stores Commission ({onboardedStores.length})
        </button>
        <button 
          onClick={() => setActiveSubTab('payouts')}
          className={`pb-2 text-sm font-bold transition-all relative ${activeSubTab === 'payouts' ? 'text-blue-600 font-extrabold border-b-2 border-blue-600' : 'text-slate-500 hover:text-slate-800'}`}
        >
          Payslips & Payout Invoices ({payouts.length})
        </button>
      </div>

      {/* Sub Tab: Commissions */}
      {activeSubTab === 'commissions' && (
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 md:p-8">
          <h3 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2 border-b border-slate-100 pb-4">
            <BadgePercent size={20} className="text-blue-500" />
            Merchant Onboarding Commissions
          </h3>

          {onboardedStores.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200 text-xs font-bold text-slate-500 uppercase tracking-wider">
                    <th className="px-6 py-4">Onboarded Store</th>
                    <th className="px-6 py-4">Plan Selected</th>
                    <th className="px-6 py-4">Store Paid Amount</th>
                    <th className="px-6 py-4">Commission Percentage</th>
                    <th className="px-6 py-4">Commission Earned</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-sm">
                  {onboardedStores.map((store, index) => (
                    <tr key={index} className="hover:bg-slate-50/50 transition">
                      <td className="px-6 py-4">
                        <div className="font-bold text-slate-800">{store.storeName}</div>
                        <div className="text-xs text-slate-400 font-medium">
                          {store.subdomain}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        {store.hasSelectedPlan ? (
                          <div className="space-y-0.5">
                            <span className="px-2 py-0.5 bg-green-50 text-green-700 text-xs font-bold rounded-full">
                              Selected {store.firstPaymentPlan}
                            </span>
                            {store.firstPaymentDate && (
                              <p className="text-[10px] text-slate-400 font-medium">
                                Paid on {new Date(store.firstPaymentDate).toLocaleDateString('en-IN')}
                              </p>
                            )}
                          </div>
                        ) : (
                          <span className="px-2 py-0.5 bg-amber-50 text-amber-700 text-xs font-bold rounded-full">
                            Free / Trial (No Selected Plan)
                          </span>
                        )}
                      </td>
                      <td className="px-6 py-4 font-bold text-slate-800">
                        ₹{store.planPaidAmount.toLocaleString('en-IN')}
                      </td>
                      <td className="px-6 py-4 font-semibold text-slate-600">
                        {commissionPercentage}%
                      </td>
                      <td className="px-6 py-4 font-extrabold text-blue-600">
                        ₹{store.commissionEarned.toLocaleString('en-IN')}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="text-center py-12">
              <div className="h-16 w-16 bg-slate-50 text-slate-400 flex items-center justify-center rounded-full mx-auto mb-4 border border-slate-200">
                <BadgePercent size={28} />
              </div>
              <h4 className="text-base font-bold text-slate-700">No Stores Onboarded</h4>
              <p className="text-sm text-slate-500 mt-1">
                You haven't onboarded any stores on the platform yet. Onboard stores and assist them in purchasing a plan to earn commission.
              </p>
            </div>
          )}
        </div>
      )}

      {/* Sub Tab: Payouts */}
      {activeSubTab === 'payouts' && (
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 md:p-8">
          <h3 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2 border-b border-slate-100 pb-4">
            <FileText size={20} className="text-green-500" />
            Payslips & Invoices Released
          </h3>

          {loadingPayouts ? (
            <div className="text-center py-12 text-slate-500 font-bold">Loading payouts history...</div>
          ) : payouts.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200 text-xs font-bold text-slate-500 uppercase tracking-wider">
                    <th className="px-6 py-4">Invoice ID</th>
                    <th className="px-6 py-4">Billing Month</th>
                    <th className="px-6 py-4">Invoice Type</th>
                    <th className="px-6 py-4">Amount Paid</th>
                    <th className="px-6 py-4">Release Date</th>
                    <th className="px-6 py-4">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-sm">
                  {payouts.map((item, index) => (
                    <tr key={index} className="hover:bg-slate-50/50 transition">
                      <td className="px-6 py-4 font-bold text-slate-800">
                        {item.invoiceId || 'N/A'}
                      </td>
                      <td className="px-6 py-4 font-semibold text-slate-700">
                        {item.month}
                      </td>
                      <td className="px-6 py-4 capitalize font-semibold">
                        <span className={`px-2 py-0.5 rounded text-xs ${item.type === 'salary' ? 'bg-indigo-50 text-indigo-700' : 'bg-teal-50 text-teal-700'}`}>
                          {item.type}
                        </span>
                      </td>
                      <td className="px-6 py-4 font-extrabold text-slate-800">
                        ₹{(item.amount || 0).toLocaleString('en-IN')}
                      </td>
                      <td className="px-6 py-4 text-slate-500">
                        {item.paidAt ? new Date(item.paidAt).toLocaleDateString('en-IN', { dateStyle: 'medium' }) : 'N/A'}
                      </td>
                      <td className="px-6 py-4">
                        <span className="px-2.5 py-0.5 bg-green-50 text-green-700 text-xs font-bold rounded-full flex items-center gap-1 w-fit">
                          <CheckCircle size={12} /> {item.status || 'Paid'}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="text-center py-12">
              <div className="h-16 w-16 bg-slate-50 text-slate-400 flex items-center justify-center rounded-full mx-auto mb-4 border border-slate-200">
                <FileText size={28} />
              </div>
              <h4 className="text-base font-bold text-slate-700">No Generated Payouts</h4>
              <p className="text-sm text-slate-500 mt-1">
                The administrator has not generated or processed any salary or commission payouts for you yet.
              </p>
            </div>
          )}
        </div>
      )}

      {/* Help Alert Box */}
      <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6 flex flex-col md:flex-row gap-6 items-start md:items-center">
        <div className="p-3 bg-blue-50 rounded-xl text-blue-600 shrink-0">
          <HelpCircle size={24} />
        </div>
        <div>
          <h4 className="font-bold text-slate-800 text-base mb-1">Earning Policy & Release cycles</h4>
          <p className="text-sm text-slate-600 font-medium leading-relaxed">
            Commissions are paid directly to your registered bank account or UPI ID. One-time commissions are registered automatically when the client purchases/selects a subscription. Invoices and payouts are released monthly.
          </p>
        </div>
      </div>
    </div>
  );
};

export default EarningTab;
